#!/usr/bin/env python3

import json
import re
from pathlib import Path

from jsonc import (
    load_jsonc,
    has_jsonc_content,
    find_last_significant_index,
)

HOME = Path.home()

REGISTRY = HOME / "vsetup/dir/registry"

GLOBAL_KEYBINDINGS = (
    HOME
    / "Library/Application Support/Code/User/keybindings.json" 
)

VSETUP_START = "// ---------- vsetup:start ----------"
VSETUP_END = "// ---------- vsetup:end ----------"


# ---------------------------------------------------------
# Transformation
# ---------------------------------------------------------

def make_repo_condition(repo: Path) -> str:
    """
    Create the VS Code 'when' condition that restricts a
    keybinding to files inside this repository.
    """

    escaped = re.escape(str(repo))

    # VS Code uses /.../ for regex literals, so path slashes
    # need to be escaped.
    escaped = escaped.replace("/", r"\/")

    return f"resourceDirname =~ /^{escaped}(?:\\/|$)/"


def transform_binding(binding: dict, repo: Path) -> dict:
    """
    Convert a repo-level vsetup keybinding into a real
    VS Code keybinding.
    """

    result = dict(binding)

    repo_condition = make_repo_condition(repo)
    existing_when = result.get("when")

    if existing_when:
        result["when"] = (
            f"({existing_when}) && ({repo_condition})"
        )
    else:
        result["when"] = repo_condition

    return result


# ---------------------------------------------------------
# Compile repos
# ---------------------------------------------------------

def get_repos():
    if not REGISTRY.exists():
        return []

    repos = []
    seen = set()

    for line in REGISTRY.read_text(encoding="utf-8").splitlines():
        line = line.strip()

        if not line:
            continue

        # Avoid compiling the same repo twice.
        if line in seen:
            continue

        seen.add(line)
        repos.append(Path(line))

    return repos


def compile_repo(repo: Path):
    path = repo / ".vsetup/keybindings.json"

    if not path.exists():
        return []

    bindings = load_jsonc(path)

    if not isinstance(bindings, list):
        raise ValueError(
            f"{path} must contain a JSON array."
        )

    compiled = []

    for i, binding in enumerate(bindings):
        if not isinstance(binding, dict):
            raise ValueError(
                f"{path}: keybinding #{i + 1} must be an object."
            )

        compiled.append(
            transform_binding(binding, repo)
        )

    return compiled


def compile_repos(repos):
    """
    Compile every repo exactly once.

    Returns:
        [
            (repo_path, [binding1, binding2, ...]),
            ...
        ]
    """

    compiled_repos = []

    for repo in repos:
        bindings = compile_repo(repo)

        if bindings:
            compiled_repos.append(
                (repo, bindings)
            )

    return compiled_repos


# ---------------------------------------------------------
# Generate vsetup section
# ---------------------------------------------------------

def indent_block(
    text: str,
    indent: str = "    ",
) -> str:
    return "\n".join(
        indent + line if line.strip() else line
        for line in text.splitlines()
    )


def generate_vsetup_block(compiled_repos):
    """
    Generate the entire vsetup-owned keybindings block.

    All generated bindings are treated as one sequence,
    regardless of repo boundaries. Therefore every binding
    except the final binding receives a comma.
    """

    lines = [
        VSETUP_START,
        "// AUTO-GENERATED BY vsetup. DO NOT EDIT THIS SECTION MANUALLY.",
        "// DO NOT ADD KEYBINDINGS AFTER THIS.",
        "",
    ]

    total_bindings = sum(
        len(bindings)
        for _, bindings in compiled_repos
    )

    binding_index = 0

    for repo, bindings in compiled_repos:
        lines.append(
            f"// ---------- vsetup:repo:start {repo} ----------"
        )

        for binding in bindings:
            binding_index += 1

            json_text = json.dumps(
                binding,
                indent=4,
                ensure_ascii=False,
            )

            # Every generated binding except the last one
            # needs a comma.
            if binding_index < total_bindings:
                json_text += ","

            lines.append(json_text)

        lines.append(
            f"// ---------- vsetup:repo:end {repo} ----------"
        )

        lines.append("")

    lines.append(VSETUP_END)

    return "\n".join(lines)

# ---------------------------------------------------------
# vsetup block management
# ---------------------------------------------------------

def remove_old_vsetup_block(text: str) -> str:
    """
    Remove the previously generated vsetup section.
    """

    start_count = text.count(VSETUP_START)
    end_count = text.count(VSETUP_END)

    if start_count != end_count:
        raise ValueError(
            "Malformed vsetup section in global keybindings: "
            "start/end markers do not match."
        )

    if start_count > 1:
        raise ValueError(
            "Multiple vsetup sections found in global keybindings."
        )

    if start_count == 0:
        return text

    pattern = (
        re.escape(VSETUP_START)
        + r".*?"
        + re.escape(VSETUP_END)
    )

    return re.sub(
        pattern,
        "",
        text,
        count=1,
        flags=re.DOTALL,
    )


# ---------------------------------------------------------
# Global keybindings management
# ---------------------------------------------------------

def write_global_keybindings(repos):
    GLOBAL_KEYBINDINGS.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # If the file does not exist at all, create a normal empty array.
    if not GLOBAL_KEYBINDINGS.exists():
        GLOBAL_KEYBINDINGS.write_text(
            "[]\n",
            encoding="utf-8",
        )

    text = GLOBAL_KEYBINDINGS.read_text(
        encoding="utf-8"
    )

    # Compile FIRST.
    #
    # If any repo contains invalid JSON, compilation fails
    # before touching the global keybindings file.
    compiled_repos = compile_repos(repos)

    has_vsetup_bindings = bool(compiled_repos)

    # If the global file contains only comments/whitespace,
    # preserve those comments and add an empty array beneath them.
    if not has_jsonc_content(text):
        comments = text.rstrip()

        if comments:
            text = comments + "\n\n[]\n"
        else:
            text = "[]\n"

    # Remove whatever vsetup generated last time.
    text = remove_old_vsetup_block(text)

    # Find the final closing bracket of the top-level array.
    closing = text.rfind("]")

    if closing == -1:
        raise ValueError(
            f"{GLOBAL_KEYBINDINGS} does not contain "
            "a closing array bracket."
        )

    before = text[:closing].rstrip()
    after = text[closing:]

    # Find the last real, non-comment, non-whitespace character.
    last_index = find_last_significant_index(before)

    has_existing_bindings = (
        last_index is not None
    )

    # Add a separator comma only when:
    #
    # - there are already user keybindings
    # - vsetup actually generated at least one keybinding
    # - the existing section does not already end in a comma
    #
    if (
        has_existing_bindings
        and has_vsetup_bindings
        and before[last_index] != ","
    ):
        before = (
            before[:last_index + 1]
            + ","
            + before[last_index + 1:]
        )

    block = generate_vsetup_block(
        compiled_repos
    )

    block = indent_block(block)

    new_text = (
        before
        + "\n\n"
        + block
        + "\n"
        + after.lstrip()
    )

    GLOBAL_KEYBINDINGS.write_text(
        new_text,
        encoding="utf-8",
    )

# ---------------------------------------------------------
# Main
# ---------------------------------------------------------

def main():
    repos = get_repos()

    write_global_keybindings(repos)

    print("Compiled keybindings.")
    print(f"Updated: {GLOBAL_KEYBINDINGS}")
    print(f"Registered repos: {len(repos)}")


if __name__ == "__main__":
    main()